# Basic Information 
title: Zhongchi Li
position: Social Psychology PhD Student
affiliation: University of Florida
#affiliation_link: https://cs.jhu.edu/
affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: zhongchili@ufl.edu
#email2: yliu538 (at) jhu.edu

# Search Engine Optimization (SEO)
keywords: zhongchi li, li zhongchi, lizhongchi, zhongchili, zhongchili uf
canonical: https://zhongchili52.github.io
description: Zhongchi Li's Personal Website

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
#github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/zhongchili/
twitter: https://twitter.com/ZhongchiLi52/

# Images 
avatar: ./assets/img/favicon.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
#footnote: 
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
